---
version: "3"
services:
   application:
        build: ./Docker-app
        container_name: application
        ports:
          - "1234:8080"
        depends_on:
              - "database"
   database:
      build: ./Docker-db
      container_name: devopsdb
      ports:
        - "3306:3306"
