---
version: "3"
services:
   application:
        image: kothapallishiva/newrepo:appimage
        deploy:
          replicas: 3
        ports:
          - "8080"
        depends_on:
              - "devopsdb"
   devopsdb:
      image: kothapallishiva/newrepo:dbimage
      ports:
        - "3306:3306"
